export const ROUTES = {
  admin: '/admin',
  adminLogin: '/admin/login',
  adminOrders: '/admin/orders',
  adminProducts: '/admin/products',
  adminUsers: '/admin/users',
  cart: '/cart',
  forgotPassword: '/forgot-password',
  home: '/',
  login: '/login',
  oauthCallback: '/oauth2/callback',
  orderDetail: (id) => `/orders/${id}`,
  orders: '/orders',
  profile: '/profile',
  productDetail: (id) => `/products/${id}`,
  products: '/products',
  register: '/register',
  resetPassword: '/reset-password',
  wishlist: '/wishlist',
}
